# This rule is not used by the project secret-sync-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to sync.example.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: secret-sync-controller
    app.kubernetes.io/managed-by: kustomize
  name: secretsync-viewer-role
rules:
- apiGroups:
  - sync.example.com
  resources:
  - secretsyncs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sync.example.com
  resources:
  - secretsyncs/status
  verbs:
  - get
