apiVersion: sync.example.com/v1alpha1
kind: SecretSync
metadata:
  labels:
    app.kubernetes.io/name: secret-sync-controller
    app.kubernetes.io/managed-by: kustomize
  name: secretsync-sample
spec:
  # TODO(user): Add fields here
